### ISSUE TITLE
SetVentana debería recibir un IVista?

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#102]
Actualmente está así

(controlador->Parser.java->)
![image](https://user-images.githubusercontent.com/54629467/66705922-4fbd4680-ed03-11e9-85f4-694c4e86e70b.png)

Pero aprovechando que tenemos la IVista creo q podríamos chantarle objeto tipo IVista

**Comment by Tostadora1** [comment]
HACIENDO
