### ISSUE TITLE
Hay error con un JButton, una pila de errores en la ventana. 

### ISSUE THREAD

**Issue by NavarroFer** [NavarroFer/Taller1#125]
![image](https://user-images.githubusercontent.com/49495922/66709012-a17cc580-ed31-11e9-8197-3d7859ebdddb.png)

No esta el boton xd

**Comment by Tostadora1** [comment]
ya seeeeeeeeeeeeeee leer #123

**Comment by NavarroFer** [comment]
donde esta el 123 aaah

**Comment by NavarroFer** [comment]
ahi lo viiii aaaaaaaaaaaaaaaaaaa
