### ISSUE TITLE
Cuando dejas el mouse sobre paneles de la ventana dice rucula

### ISSUE THREAD

**Issue by JPCard** [NavarroFer/Taller1#131]
Lo de arriba

**Comment by NahuelM97** [comment]
ez sierto

![image](https://user-images.githubusercontent.com/54629467/66719916-6085bf00-edcc-11e9-8056-8fffa721d91b.png)

**Comment by NahuelM97** [comment]
fixing

**Comment by NahuelM97** [comment]
bueno ese pedazo de codigo no se puede editar porque esta como protegido, así que tuve que pergeniarme un workaround
