### ISSUE TITLE
Implementación del método "insertar" del modelo

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#25]
Implementación del método "insertar" del modelo, ubicado en la clase Sistema, la cual responde a la ejecución de la instrucción de consola **insertar**

**Comment by Tostadora1** [comment]
ya estaba semi hecho, lo complete, y anda, pero la verificacion de si el archivo q se quiere insertar existe o no hay que hacerla en el controlador, o en el modelo? actualmente se hace  en el model oy si el archivo no existe hace un SOP() lo cual es medio raro.

**Comment by NahuelM97** [comment]
parece que ya funciona como es esperado
