### ISSUE TITLE
Corrección del método cargar

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#26]
Corrección del método "cargar" del modelo, ubicado en la clase Sistema, el cual no hace lo requerido en el SRS

**Comment by Tostadora1** [comment]
este hace lo mismo que cargar? o no? por si acaso lo dejo abierto

**Comment by NahuelM97** [comment]
_cargar_ está en la capa de negocios y se ocupa de todas las verificaciones y de la invocación al método del modelo.
_cargarPersistentes_ esta en el modelo y debería ser la implementación sin ningún tipo de chequeo de lo solicitado por consigna

**Comment by NahuelM97** [comment]
Si, alguien cambió el nombre en algún momento jeje. Básicamente sacarle los SOP y dejarlo bonito si le falta algún detalle. Y que claramente no patee la exception para arriba
