### ISSUE TITLE
Implementación del método "insertar" del controlador

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#28]
Implementación del método "insertar" del controlador, ubicado en la clase Parser, la cual responde a la ejecución de la instrucción de consola insertar

**Comment by Tostadora1** [comment]
funciona, pero quizas deberia revisra a la altura del controlador si el archivo a insertar existe o no

**Comment by NahuelM97** [comment]
Después creamos otro issue para eso
