### ISSUE TITLE
Implementación del método "consultar" del controlador

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#29]
Implementación del método "consultar" del modelo, ubicado en la clase Sistema, la cual responde a la ejecución de la instrucción de consola **consultar**

**Comment by Tostadora1** [comment]
esto no lo hice pp ppp

**Comment by NahuelM97** [comment]
entonces no comentes salame jajajajajaj

**Comment by nachoviejo** [comment]
Hice esto según lo que respondió Adolfo. Faltaría ver como mostramos el listado de los alumnos.
