### ISSUE TITLE
Feedback desde la consola

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#48]
Necesitamos agregar feedback de la consola para que el usuario sepa que su comando fue ejecutado con éxito

Ejemplo:
Funcionamiento actual: (Lo que se ve en la consola)
```
crear almacen2.alm
insertar alumnotext.xml
```

Funcionamiento deseado: (Lo que se desearía ver en la consola)
```
crear almacen2.alm
Almacén creado con éxito
insertar alumnotext.xml
Alumno cargado con éxito
```

**Comment by Tostadora1** [comment]
mergeamelooo ya lo arrelgeeeeeeeeeeeeeeeeeee
