### ISSUE TITLE
Si el archivo existe pero no es del tipo que corresponde se rompe

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#50]
Auto-explicativo. 

Si uno pone 

```
cargar alumno.xml
```
va a efectivamente intentar cargar un alumno a almacén.

**Comment by Tostadora1** [comment]
para adolf: cuando queres importar un xml y el tipo esta incorrecto, tiramos una excepcion del modelo, o llo preleemos en el parser para q no llegue tan abajo???

**Comment by NahuelM97** [comment]
Implementada la corrección. Falta preguntar

**Comment by NahuelM97** [comment]
Cuando querés importar un XML y el archivo sí existe pero la clase que contiene no corresponde a una clase, quién debería detectar eso? 
- El parser? Para ello el parser debería abrir el archivo y leer su contenido (entonces efectivamente leer 2 veces)
- El modelo? Para ello debería ocuparse de tirar la excepción de "ClassCastException" (Modelo tirando excepción?)

**Comment by NahuelM97** [comment]
quien vota por poner

Precondicion: El archivo es un XML válido y del tipo correcto

comenten vot si y dejen un like

**Comment by NahuelM97** [comment]
vot si

**Comment by JPCard** [comment]
voto por modelo tirando excepcion

**Comment by Tostadora1** [comment]
peligro de robo

**Comment by Tostadora1** [comment]
lean el coment de nahue que anexe mi duda

**Comment by NavarroFer** [comment]
que coment @Tostadora1 ?

**Comment by Tostadora1** [comment]
![image](https://user-images.githubusercontent.com/8041692/66720428-f3c1f300-edd2-11e9-8a28-24e6985a3864.png)

**Comment by JPCard** [comment]
si, pero eso habían dicho que convenía resolverlo abriendo una sola vez en modelo creo.
Una vez guille habia dicho que en la practica a veces el modelo tira excepciones
