### ISSUE TITLE
Guardar archivos en subdirectorio "Datos"

### ISSUE THREAD

**Issue by JPCard** [NavarroFer/Taller1#54]
El archivo de persistencia(consultar con toFile) se guarda en un subdirectorio llamado “Datos”, ubicado
dentro del directorio donde se encuentran los ejecutables de la aplicación.

**Comment by Tostadora1** [comment]
![image](https://user-images.githubusercontent.com/8041692/64928073-6e561d80-d7e9-11e9-8344-e990b51d308d.png)

**Comment by Tostadora1** [comment]
1321541687446565
