### ISSUE TITLE
Agregar minsize a la ventana

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#59]
Agregar tamaño minimo a la ventana para que no se pueda resizear hasta tan chiquita porque queda re chori xd

**Comment by NavarroFer** [comment]
ya lo tiene xd

**Comment by NavarroFer** [comment]
min
![imagen](https://user-images.githubusercontent.com/49495922/65530593-ab4b9f80-dece-11e9-8eb2-cb4e1ec2ef12.png)

normal
![imagen](https://user-images.githubusercontent.com/49495922/65530627-bb637f00-dece-11e9-8b5f-07f0146904ee.png)
