### ISSUE TITLE
Método insertar del modelo no verifica si no existe la misma id

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#66]
Método insertar del modelo no verifica si no existe otro alumno con la misma ID. Debería utilizar alumnoExists() (creo que se llama así)

**Comment by Tostadora1** [comment]
![image](https://user-images.githubusercontent.com/8041692/64928079-829a1a80-d7e9-11e9-8f62-9a73fd46f56a.png)
