### ISSUE TITLE
Documentar el método consultar y aclarar que es case sensitive

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#67]
Básicamente en función de lo decidido en #60

**Comment by NahuelM97** [comment]
Considerar la posibilidad de notificar al usuario de esto. Por ej, si se detecta que el archivo no existe, printear en pantalla "El archivo no fue encontrado. Recuerde que debe respetar las mayúsculas!" o algo así.

**Comment by nachoviejo** [comment]
El metodo consultar no es case sensitive. Cuando evalua el nombre de archivo ingresado hace un toUpper y te lo muestro troesma
![Captura](https://user-images.githubusercontent.com/54726362/66705280-efc2a200-ecfa-11e9-9185-3e3ef921f6a3.PNG)

**Comment by NahuelM97** [comment]
Es cierto, el TOFILE no es case sensitive, a lo que se refería el issue es al nombre de una materia (Por ej si la materia se llama Orga y vos pones orga te dice que no existe)

![image](https://user-images.githubusercontent.com/54629467/66705966-c3f7ea00-ed03-11e9-97c5-db205f15ff89.png)
