### ISSUE TITLE
Si el CONSULTAR no tiene exito, se muestra por consola: "[]" (corchetes xd)

### ISSUE THREAD

**Issue by NavarroFer** [NavarroFer/Taller1#81]

**Comment by JPCard** [comment]
es porque printea la lista de alumnos que cumplen pero esa lista esta vacia

**Comment by NavarroFer** [comment]
No se puede editar eso? o sea habria que hacer el toString() a mano no??

**Comment by NavarroFer** [comment]
En vez de enviar el array y que se le haga toString() dentro del controlador. Que llegue un String y mostrarlo. Si es vacio, mostrar mensaje que no hubo éxito en la CONSULTA.

**Comment by Tostadora1** [comment]
![image](https://user-images.githubusercontent.com/8041692/66260491-ba1b3780-e795-11e9-997e-47a17436dbc6.png)

 hice lo que dijo fer

![image](https://user-images.githubusercontent.com/8041692/66260732-01ef8e00-e799-11e9-9ad9-49d3262c9880.png)
