### ISSUE TITLE
Cuando ejecutas el comando CARGAR, y el archivo existe(todo bien). Por la consola de ERRORES sale un "0" CERO 

### ISSUE THREAD

**Issue by NavarroFer** [NavarroFer/Taller1#82]

**Comment by JPCard** [comment]
ese error viene de la mano con el #83 ya que el objeto no se guarda bien no se puede cargar y se queda colgada la operacion de carga.

**Comment by Tostadora1** [comment]
a ver este

**Comment by Tostadora1** [comment]
Ahi lo arregle haciendo q almacen implemente Serializable y tenga un constructor vacio que no hace nada
