### ISSUE TITLE
Comando GUARDAR "anda bien" pero tira excepcion en consola de JDeveloper

### ISSUE THREAD

**Issue by NavarroFer** [NavarroFer/Taller1#83]
![imagen](https://user-images.githubusercontent.com/49495922/66174205-47da1400-e62a-11e9-9040-dc59feb386fe.png)

**Comment by JPCard** [comment]
No anda bien del todo solo llega hasta la parte de crear el archivo y no le pone el objeto serializado porque no puede hacerlo porque debe tener:
 

- un constructor publico sin parametros

- tiene que implementar serializable

- tiene que tener getters y setters publicos de todos sus atributos

**Comment by Tostadora1** [comment]
y acompaño con un poco de este

**Comment by Tostadora1** [comment]
Ahi lo arregle haciendo q almacen implemente Serializable y tenga un constructor vacio que no hace nada
