### ISSUE TITLE
[IMPORTANTE]

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#85]
Si hiciste un método y es case sensitive aclaralo en la documentación del método.

```
 /*
 * [...]
 * @param (parametro) [...] y también, este parámetro es case sensitive
 * [...]
 */
```

Esto es estrictamente necesario pues en el parser se encuentra documentado lo siguiente:
[...]
Nota: Todas las instrucciones y la mayoría de los parámetros no son case sensitive. Para saber exactamente cuales son case sensitive y cuales no, remitirse a la documentación del modelo. En caso de no aclararse se asume que no es case sensitive.
[...]

Sería inviable aclarar cuales sí son y cuales no en la documentación del parser. No sólo quedaría larguísimo sino que me tendría que romper la jeta leyendo todo jeje saludos

**PD si ya leíste este issue comentá algo. Cuando lo hayan leído todos lo cierro.**

**Comment by nachoviejo** [comment]
lei3

**Comment by NavarroFer** [comment]
Ok. Entonces se comentan los case sensitive

**Comment by JPCard** [comment]
k

**Comment by Tostadora1** [comment]
![image](https://user-images.githubusercontent.com/8041692/66260473-7d4f4080-e795-11e9-92c3-6a186b6cc31c.png)
