### ISSUE TITLE
[Importante también xd] Si crean un método largo o complejo...

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#87]
Si crean un método que es muy largo o muy complejo, por favor, añadan a la documentación del mismo "@author yourname". Esto es para que cuando otro tenga que editar o consultar ese método por algún motivo sea cual sea, sepa a quien preguntar por cualquier cosa.
Si un método muy grande o muy complejo está hecho por mas de uno usar "@authors name1, name2, etc"

Igual que el importante anterior, comenten cuando leen por favor

**Comment by NavarroFer** [comment]
oka chufy

**Comment by Tostadora1** [comment]
hola

**Comment by JPCard** [comment]
> guarda chufi dema
