### ISSUE TITLE
Crear una clase Controlador parte del paquete de controlador

### ISSUE THREAD

**Issue by JPCard** [NavarroFer/Taller1#93]
Esta clase tiene como funcion ser intermediario entre la vista y la capa de Negocios, por lo que va a recibir el pedido de parseo de la ventana por medio de un evento (EventListener).
Por su parte la clase Parser pasaria a ser del paquete Negocios

La voy a hacer yo porque como a mi se me ocurrió y soy un tipo con iniciativa lo voy a hacer yo

**Comment by NahuelM97** [comment]
en que te metiste...!!!!

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709374-3c2cd280-ed39-11e9-92dd-5afd1dd31a5b.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709379-4d75df00-ed39-11e9-9994-9e378dd67d50.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709381-52d32980-ed39-11e9-81df-22b66836bb76.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709383-59fa3780-ed39-11e9-9689-4896acfd5e40.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709384-63839f80-ed39-11e9-8ec3-95736a7414a7.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709387-844bf500-ed39-11e9-9c9b-ff326012e8d1.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709396-c117ec00-ed39-11e9-9396-753d76d5f8f3.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709400-cbd28100-ed39-11e9-9f97-ffc76068d59e.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66709414-1b18b180-ed3a-11e9-8f20-d46690232d95.png)
