### ISSUE TITLE
Hacer lo mismo que hicimos para el consultar para elconsultar con toFile?

### ISSUE THREAD

**Issue by Tostadora1** [NavarroFer/Taller1#94]
Me refiero a, si alguien hace un consultar con toFile, y no hay resultados. Ahora supongo que esta haciendo un archivo con un [] adentro, deberiamos hacer que escriba "No hay alumnos qcumplan etc etc" como su hermano de consola?

primo de #81

**Comment by NahuelM97** [comment]
vot si

y que no genere el file asumo
