### ISSUE TITLE
Agregar invariantes de clase

### ISSUE THREAD

**Issue by NahuelM97** [NavarroFer/Taller1#98]
Si por casualidad tienen algun invariante de clase agreguenlo, lo digo pq yo me acabo de acordar que me olvide que existia eso xDd slau2

**Comment by Tostadora1** [comment]
se realizo la agregasion?
![image](https://user-images.githubusercontent.com/8041692/66707581-18f22b00-ed19-11e9-8060-8894f164702b.png)

**Comment by NahuelM97** [comment]
![image](https://user-images.githubusercontent.com/54629467/66707586-26a7b080-ed19-11e9-91af-5f4e9eca6ee1.png)

**Comment by NavarroFer** [comment]
a ber
